worker_processes  1;

events {
  worker_connections  1024;
}

http {
  server {
    listen 8080;
    server_name   _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    error_page 404 /404.html;
    location = /404.html {
      root /usr/share/nginx/html;
      internal;
    }

    location = /p.js {
      proxy_pass https://plausible.johnprutton.dev/js/script.outbound-links.tagged-events.js;
      proxy_set_header Host plausible.johnprutton.dev;
      proxy_buffering on;
      proxy_cache jscache;
      proxy_cache_valid 200 5m;
      proxy_cache_use_stale updating error timeout invalid_header http_500;

      add_header X-Cache $upstream_cache_status;
    }

    location = /api/event {
      proxy_pass https://plausible.johnprutton.dev/api/event;
      proxy_set_header Host plausible.johnprutton.dev;
      proxy_buffering on;
      proxy_http_version 1.1;

      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host  $host;
    }

    location / {
      try_files $uri $uri/index.html =404;
    }
  }
}
